<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Team CodeNexus">
<meta name="dcterms.date" content="2026-04-24">

<title>report</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Predicting Stroke Risk Using Patient Health and Lifestyle Data</h1>
<p class="subtitle lead">Data Analysis Report</p>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Team CodeNexus </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            University of Moratuwa
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 24, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="team-details" class="level2">
<h2 class="anchored" data-anchor-id="team-details">Team Details</h2>
<p><strong>Team Name:</strong> CodeNexus<br>
<strong>University:</strong> University of Moratuwa<br>
<strong>Team Members:</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Student ID</th>
<th>Primary Contributions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R.P.M. Vithanage</td>
<td>[ID]</td>
<td>Data cleaning, deduplication, BMI imputation, EDA</td>
</tr>
<tr class="even">
<td>S.E.N. S. Silva</td>
<td>[ID]</td>
<td>Statistical testing, feature engineering, visualisations, modelling</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="abstract" class="level2">
<h2 class="anchored" data-anchor-id="abstract">Abstract</h2>
<p>This report presents a stroke risk prediction study built on patient health and lifestyle data. The original dataset contained 9,722 records, but deduplication revealed 4,612 exact clinical duplicates that had artificially inflated the stroke positive class. After correction, the true dataset contains 5,110 unique patients with a stroke prevalence of 4.87%, consistent with published real-world clinical rates.</p>
<p>The analysis combines exploratory data analysis, statistical hypothesis testing, feature engineering, and a leakage-safe machine learning pipeline. Five models are evaluated and they are Logistic Regression, Random Forest, XGBoost, Soft Voting Ensemble, and a Stacking Ensemble using out-of-fold meta learning. Under a clinically appropriate High Sensitivity operating mode, Logistic Regression achieves the highest recall (0.940), missing only 3 stroke patients out of 50 in the test set. The Stacking Ensemble achieves the best overall precision-recall performance (AUC-PR = 0.215). A key finding is that simpler regularised models can outperform gradient boosting on recall when the minority class is small, due to the bias variance tradeoff.</p>
<hr>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">1. Introduction</h2>
<section id="background-and-motivation" class="level3">
<h3 class="anchored" data-anchor-id="background-and-motivation">1.1 Background and Motivation</h3>
<p>Stroke is a major global health problem and a leading cause of death and long-term disability. The World Health Organization estimates that approximately 15 million people experience a stroke each year, with roughly 5 million deaths and another 5 million people left permanently disabled. Stroke can cause paralysis, speech impairment, cognitive dysfunction, and vision loss, placing a significant and growing burden on healthcare systems worldwide.</p>
<p>Early identification of patients at high stroke risk allows clinicians to intervene before a cerebrovascular event occurs, reducing both clinical severity and long term rehabilitation costs. Despite advances in medical data collection, transforming large volumes of patient records into actionable risk predictions remains a central challenge in healthcare analytics.</p>
</section>
<section id="problem-statement" class="level3">
<h3 class="anchored" data-anchor-id="problem-statement">1.2 Problem Statement</h3>
<p>This study addresses the challenge of predicting stroke events using a dataset of 9,722 patient records collected by a healthcare organisation. After removing duplicate records introduced through an artificial balancing procedure, the true dataset contains 5,110 unique patients with a stroke prevalence of 4.87%. The analysis addresses three core objectives:</p>
<ul>
<li>Develop a machine learning pipeline capable of accurately predicting stroke events in the presence of severe class imbalance</li>
<li>Identify the most clinically influential risk factors contributing to stroke occurrence</li>
<li>Generate evidence-based insights to support preventive healthcare strategies and early screening protocols</li>
</ul>
</section>
<section id="significance-of-the-study" class="level3">
<h3 class="anchored" data-anchor-id="significance-of-the-study">1.3 Significance of the Study</h3>
<p>A key contribution of this study is the identification and correction of an artificial dataset imbalance. The original 9,722 records contain 4,612 exact clinical duplicates concentrated entirely in the stroke-positive class, inflating a naturally rare event to a misleadingly balanced 50/50 distribution. Models trained on this artificially balanced data produce inflated performance metrics that do not reflect real-world deployment conditions. This study works exclusively with the 5,110 deduplicated records, employing SMOTE oversampling, class-weight adjustment, and threshold tuning to address the genuine imbalance in a methodologically sound manner.</p>
<hr>
</section>
</section>
<section id="dataset-and-preprocessing" class="level2">
<h2 class="anchored" data-anchor-id="dataset-and-preprocessing">2. Dataset and Preprocessing</h2>
<section id="dataset-description" class="level3">
<h3 class="anchored" data-anchor-id="dataset-description">2.1 Dataset Description</h3>
<p>The dataset contains 17 variables covering demographics,medical history , lifestyle habits, and clinical measurements, with <code>stroke_event</code> as the binary target variable.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Type</th>
<th>Description</th>
<th>Modelling Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>patient_id</code></td>
<td>Identifier</td>
<td>Unique record identifier</td>
<td>Excluded</td>
</tr>
<tr class="even">
<td><code>gender</code></td>
<td>Categorical</td>
<td>Patient gender (M / F)</td>
<td>Encoded (label)</td>
</tr>
<tr class="odd">
<td><code>age</code></td>
<td>Continuous</td>
<td>Age in years — strongest predictor (r = 0.243)</td>
<td>Retained</td>
</tr>
<tr class="even">
<td><code>age_group</code></td>
<td>Categorical</td>
<td>Binned age: young / middle / senior</td>
<td>Excluded because redundant with age</td>
</tr>
<tr class="odd">
<td><code>has_hypertension</code></td>
<td>Binary</td>
<td>Presence of hypertension (1 = Yes)</td>
<td>Retained</td>
</tr>
<tr class="even">
<td><code>has_heart_disease</code></td>
<td>Binary</td>
<td>Presence of heart disease (1 = Yes)</td>
<td>Retained</td>
</tr>
<tr class="odd">
<td><code>marital_status</code></td>
<td>Binary</td>
<td>Marital status (1 = Married)</td>
<td>Retained</td>
</tr>
<tr class="even">
<td><code>employment_type</code></td>
<td>Categorical</td>
<td>Work status: working / government / other</td>
<td>Encoded (label)</td>
</tr>
<tr class="odd">
<td><code>residence</code></td>
<td>Categorical</td>
<td>Urban or Rural area of residence</td>
<td>Encoded (label)</td>
</tr>
<tr class="even">
<td><code>glucose_level</code></td>
<td>Continuous</td>
<td>Blood glucose level (mg/dL)</td>
<td>Retained</td>
</tr>
<tr class="odd">
<td><code>high_glucose</code></td>
<td>Binary</td>
<td>Binary threshold of glucose_level</td>
<td>Excluded — redundant</td>
</tr>
<tr class="even">
<td><code>bmi_value</code></td>
<td>Continuous</td>
<td>Body Mass Index — 201 missing post-dedup</td>
<td>Imputed (grouped median)</td>
</tr>
<tr class="odd">
<td><code>bmi_category</code></td>
<td>Categorical</td>
<td>BMI classification</td>
<td>Excluded — redundant</td>
</tr>
<tr class="even">
<td><code>smoking_habit</code></td>
<td>Categorical</td>
<td>Smoking status (4 categories)</td>
<td>Encoded (label)</td>
</tr>
<tr class="odd">
<td><code>lifestyle_risk</code></td>
<td>Categorical</td>
<td>Composite lifestyle risk level</td>
<td>Excluded because leakage risk</td>
</tr>
<tr class="even">
<td><code>risk_score</code></td>
<td>Ordinal</td>
<td>Composite health risk score (0–2)</td>
<td>Excluded because leakage risk</td>
</tr>
<tr class="odd">
<td><code>stroke_event</code></td>
<td>Binary (Target)</td>
<td>Stroke occurrence (1 = Yes, 0 = No)</td>
<td>Target variable</td>
</tr>
</tbody>
</table>
</section>
<section id="data-integrity-duplicate-detection-and-removal" class="level3">
<h3 class="anchored" data-anchor-id="data-integrity-duplicate-detection-and-removal">2.2 Data Integrity: Duplicate Detection and Removal</h3>
<p>The original file contains 9,722 rows. After removing duplicates by comparing all clinical fields except <code>patient_id</code>, the dataset reduces to 5,110 unique patients. This correction is critical because the duplicates were concentrated entirely in the stroke-positive class. Keeping them would constitute data leakage, the model would be trained and tested on identical records, artificially inflating all performance metrics.</p>
<p>After deduplication, the true distribution is:</p>
<ul>
<li><strong>Non-stroke:</strong> 4,861 patients (95.13%)</li>
<li><strong>Stroke:</strong> 249 patients (4.87%)</li>
</ul>
<p>This prevalence is consistent with published realworld stroke incidence rates of 2–5%, validating the deduplication as clinically appropriate. A <code>risk_score</code> of 2 showed an 84.5% stroke rate and <code>lifestyle_risk = medium</code> showed 62.6% ,both disproportionately high, indicating these composite columns may have been constructed using stroke adjacent information. They were excluded from all modelling.</p>
</section>
<section id="feature-engineering" class="level3">
<h3 class="anchored" data-anchor-id="feature-engineering">2.3 Feature Engineering</h3>
<p>Seven interaction and transformation features were engineered prior to the train-test split, capturing clinically meaningful non-linear relationships that raw features cannot represent independently:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Formula</th>
<th>Clinical Rationale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>age_squared</code></td>
<td>age²</td>
<td>Nonlinear acceleration of stroke risk with advancing age</td>
</tr>
<tr class="even">
<td><code>is_senior</code></td>
<td>1 if age ≥ 55</td>
<td>Clinical threshold where stroke risk doubles per decade</td>
</tr>
<tr class="odd">
<td><code>age_x_hypertension</code></td>
<td>age × hypertension</td>
<td>Compounding interaction of the two primary risk factors</td>
</tr>
<tr class="even">
<td><code>age_x_heart_disease</code></td>
<td>age × heart disease</td>
<td>Elevated risk in older cardiac patients</td>
</tr>
<tr class="odd">
<td><code>cvd_count</code></td>
<td>hypertension + heart_disease</td>
<td>Cumulative cardiovascular disease burden (0–2)</td>
</tr>
<tr class="even">
<td><code>glucose_x_bmi</code></td>
<td>glucose × bmi</td>
<td>Joint metabolic risk of hyperglycaemia and obesity</td>
</tr>
<tr class="odd">
<td><code>log_glucose</code></td>
<td>log(glucose + 1)</td>
<td>Normalises the right-skewed glucose distribution</td>
</tr>
</tbody>
</table>
</section>
<section id="missing-value-imputation" class="level3">
<h3 class="anchored" data-anchor-id="missing-value-imputation">2.4 Missing Value Imputation</h3>
<p>After deduplication, 201 records (3.93%) have missing <code>bmi_value</code>. A grouped median imputation strategy was applied, filling each missing value with the median BMI of patients sharing the same gender and age group (young: age &lt; 40, middle: 40–60, senior: &gt; 60). This approach is more biologically accurate than a global median. Crucially, imputation statistics are computed exclusively from training data and applied to test data separately, preventing any form of imputation leakage across the train-test boundary.</p>
<p>Forward fill and backward fill were considered but rejected, these are appropriate only for timeseries data where adjacent observations are temporally related. Patient records in this dataset are independent.</p>
</section>
<section id="leakage-prevention" class="level3">
<h3 class="anchored" data-anchor-id="leakage-prevention">2.5 Leakage Prevention</h3>
<p>Two categories of features were excluded from all modelling:</p>
<ol type="1">
<li><strong>Redundant derived features</strong> that are direct functions of retained features: <code>age_group</code>, <code>bmi_category</code>, <code>high_glucose</code></li>
<li><strong>Composite scores with high leakage risk</strong>: <code>risk_score</code>, <code>lifestyle_risk</code></li>
</ol>
<p>These columns are either redundant or too closely tied to the target to be safe for honest prediction.</p>
</section>
<section id="categorical-encoding" class="level3">
<h3 class="anchored" data-anchor-id="categorical-encoding">2.6 Categorical Encoding</h3>
<p>All categorical variables were label encoded using scikit-learn’s <code>LabelEncoder</code> fitted on training data only. The four encoded features are: <code>gender</code>, <code>employment_type</code>, <code>residence</code>, and <code>smoking_habit</code>. Standard scaling was not applied to tree based models (Random Forest, XGBoost), which are invariant to feature scale. Logistic Regression used <code>class_weight='balanced'</code> as a builtin mechanism to handle the imbalanced target.</p>
<hr>
</section>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">3. Exploratory Data Analysis</h2>
<section id="class-balance" class="level3">
<h3 class="anchored" data-anchor-id="class-balance">3.1 Class Balance</h3>
<p>The corrected dataset shows the true clinical imbalance: 4,861 non-stroke cases (95.13%) and 249 stroke cases (4.87%).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals/01_class_balance.png" class="img-fluid figure-img" alt="Class balance bar chart"></p>
<figcaption>Class balance bar chart showing the true imbalanced distribution after deduplication.</figcaption>
</figure>
</div>
</section>
<section id="numeric-feature-distributions" class="level3">
<h3 class="anchored" data-anchor-id="numeric-feature-distributions">3.2 Numeric Feature Distributions</h3>
<p>Age, glucose level, and BMI all show visible differences between stroke and non-stroke patients. Age is the clearest separator, with stroke patients concentrated in the 60–80 age range. Glucose and BMI exhibit right skewed distributions that justify the log transformation and interaction features included in the engineering step.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature</th>
<th>Mean (No Stroke)</th>
<th>Mean (Stroke)</th>
<th>Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>age</td>
<td>~52.6</td>
<td>~67.7</td>
<td>+15.1 years</td>
</tr>
<tr class="even">
<td>glucose_level</td>
<td>~104.8</td>
<td>~118.3</td>
<td>+13.5 mg/dL</td>
</tr>
<tr class="odd">
<td>bmi_value</td>
<td>~28.8</td>
<td>~30.1</td>
<td>+1.3</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals/02_numeric_distributions.png" class="img-fluid figure-img" alt="Numeric distribution plots"></p>
<figcaption>Numeric feature distributions split by stroke status, showing clearly shifted age and glucose distributions.</figcaption>
</figure>
</div>
</section>
<section id="categorical-patterns" class="level3">
<h3 class="anchored" data-anchor-id="categorical-patterns">3.3 Categorical Patterns</h3>
<p>Stroke prevalence varies across groups for smoking, employment, residence, and gender. Patients with <code>smoking_habit = unknown</code> show a stroke rate comparable to current smokers, suggesting this category may capture patients reluctant to disclose their status due to existing health concerns. Gender and residence show limited independent association but contribute through interaction effects.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals/03_categorical_counts.png" class="img-fluid figure-img" alt="Categorical count plots"></p>
<figcaption>Categorical feature counts split by stroke status.</figcaption>
</figure>
</div>
</section>
<section id="boxplots-by-stroke-status" class="level3">
<h3 class="anchored" data-anchor-id="boxplots-by-stroke-status">3.4 Boxplots by Stroke Status</h3>
<p>Boxplots confirm the shift in age and glucose for the stroke class. BMI shows more overlap between groups but still contributes predictive signal , particularly through the <code>glucose_x_bmi</code> engineered feature.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals/04_boxplots.png" class="img-fluid figure-img" alt="Boxplots by stroke status"></p>
<figcaption>Boxplots of numerical features by stroke status, highlighting the age and glucose separation.</figcaption>
</figure>
</div>
</section>
<section id="correlation-analysis" class="level3">
<h3 class="anchored" data-anchor-id="correlation-analysis">3.5 Correlation Analysis</h3>
<p>The correlation matrix confirms that <code>age</code> is the strongest single numeric predictor (r = 0.243). Among engineered features, <code>age_squared</code> achieves r = 0.272 , the highest correlation with the target of any single feature ,validating the polynomial age transformation. The <code>age_x_hypertension</code> interaction (r = 0.141) outperforms either component feature independently, confirming the clinical value of the interaction term.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Feature</th>
<th>Correlation with stroke_event</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>age_squared</code></td>
<td>0.272 (highest)</td>
</tr>
<tr class="even">
<td><code>age</code></td>
<td>0.243</td>
</tr>
<tr class="odd">
<td><code>age_x_hypertension</code></td>
<td>0.141</td>
</tr>
<tr class="even">
<td><code>glucose_level</code></td>
<td>0.133</td>
</tr>
<tr class="odd">
<td><code>has_heart_disease</code></td>
<td>0.122</td>
</tr>
<tr class="even">
<td><code>has_hypertension</code></td>
<td>0.121</td>
</tr>
<tr class="odd">
<td><code>marital_status</code></td>
<td>0.104</td>
</tr>
<tr class="even">
<td><code>bmi_value</code></td>
<td>0.050</td>
</tr>
<tr class="odd">
<td><code>gender</code></td>
<td>~0.02</td>
</tr>
<tr class="even">
<td><code>residence</code></td>
<td>~0.01</td>
</tr>
</tbody>
</table>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals/05_correlation_heatmap.png" class="img-fluid figure-img" alt="Correlation heatmap"></p>
<figcaption>Correlation heatmap of numerical features and the target variable.</figcaption>
</figure>
</div>
<hr>
</section>
</section>
<section id="statistical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="statistical-analysis">4. Statistical Analysis</h2>
<section id="hypothesis-testing" class="level3">
<h3 class="anchored" data-anchor-id="hypothesis-testing">4.1 Hypothesis Testing</h3>
<p>Non-parametric Mann-Whitney U tests were used for continuous variables and chi-square tests for categorical variables. Mann-Whitney was preferred over the independent samples t-test due to non-normal distributions observed in <code>age</code> and <code>glucose_level</code>.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals/06_statistical_tests.png" class="img-fluid figure-img" alt="Statistical tests summary"></p>
<figcaption>Summary visualisation of statistical test results across all features.</figcaption>
</figure>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Feature</th>
<th>Test</th>
<th>p-value</th>
<th>Direction</th>
<th>Clinical Interpretation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>age</code></td>
<td>Mann-Whitney U</td>
<td>&lt; 0.001</td>
<td>Stroke patients older</td>
<td>Primary biological risk factor</td>
</tr>
<tr class="even">
<td><code>glucose_level</code></td>
<td>Mann-Whitney U</td>
<td>&lt; 0.001</td>
<td>Higher in stroke group</td>
<td>Hyperglycaemia promotes atherosclerosis</td>
</tr>
<tr class="odd">
<td><code>bmi_value</code></td>
<td>Mann-Whitney U</td>
<td>&lt; 0.001</td>
<td>Higher in stroke group</td>
<td>Obesity increases cardiovascular strain</td>
</tr>
<tr class="even">
<td><code>age_squared</code></td>
<td>Mann-Whitney U</td>
<td>&lt; 0.001</td>
<td>Higher in stroke group</td>
<td>Non-linear age acceleration confirmed</td>
</tr>
<tr class="odd">
<td><code>age_x_hypertension</code></td>
<td>Mann-Whitney U</td>
<td>&lt; 0.001</td>
<td>Higher in stroke group</td>
<td>Compounding risk validated statistically</td>
</tr>
<tr class="even">
<td><code>has_hypertension</code></td>
<td>Chi-Square</td>
<td>&lt; 0.001</td>
<td>—</td>
<td>Strong association with stroke</td>
</tr>
<tr class="odd">
<td><code>has_heart_disease</code></td>
<td>Chi-Square</td>
<td>&lt; 0.001</td>
<td>—</td>
<td>Strong association with stroke</td>
</tr>
<tr class="even">
<td><code>smoking_habit</code></td>
<td>Chi-Square</td>
<td>&lt; 0.001</td>
<td>—</td>
<td>Significant group differences</td>
</tr>
<tr class="odd">
<td><code>marital_status</code></td>
<td>Chi-Square</td>
<td>&lt; 0.001</td>
<td>—</td>
<td>Significant (age proxy)</td>
</tr>
<tr class="even">
<td><code>gender</code></td>
<td>Chi-Square</td>
<td>~0.12</td>
<td>—</td>
<td>No significant independent association</td>
</tr>
<tr class="odd">
<td><code>residence</code></td>
<td>Chi-Square</td>
<td>~0.18</td>
<td>—</td>
<td>No significant independent association</td>
</tr>
</tbody>
</table>
</section>
<section id="statistical-inference" class="level3">
<h3 class="anchored" data-anchor-id="statistical-inference">4.2 Statistical Inference</h3>
<p>The statistical tests support the feature engineering strategy directly. Age is not only the strongest raw predictor but also benefits from nonlinear transformation , <code>age_squared</code> achieves a higher correlation with the target than raw <code>age</code>. Cardiovascular burden works better as a combined indicator (<code>cvd_count</code>) than as isolated binary flags.</p>
<p>Gender and residence do not show statistically significant independent associations with stroke. Despite this, both features appear in the upper middle range of XGBoost feature importance. This is explained by the fact that XGBoost captures interaction effects and non linear splits involving these features, even when their marginal correlation with the target is low. Model based feature importance measures predictive contribution within the model rather than independent statistical association.</p>
<hr>
</section>
</section>
<section id="modelling-approach" class="level2">
<h2 class="anchored" data-anchor-id="modelling-approach">5. Modelling Approach</h2>
<section id="handling-class-imbalance" class="level3">
<h3 class="anchored" data-anchor-id="handling-class-imbalance">5.1 Handling Class Imbalance</h3>
<p>The class ratio is approximately 19.5:1. Three complementary strategies are employed:</p>
<ul>
<li><strong>SMOTE</strong> (Synthetic Minority Oversampling Technique): A custom k-nearest neighbours implementation generates synthetic stroke samples by interpolating between real minority class patients. Applied with <code>sampling_strategy=0.35</code> exclusively inside training folds , never to validation or test data.</li>
<li><strong><code>class_weight='balanced'</code></strong> (Logistic Regression and Random Forest): Automatically adjusts class weights inversely proportional to class frequency.</li>
<li><strong><code>scale_pos_weight</code></strong> (XGBoost only): Set to the training class ratio (~19.5), penalising missed stroke predictions more heavily during gradient computation.</li>
</ul>
</section>
<section id="model-definitions" class="level3">
<h3 class="anchored" data-anchor-id="model-definitions">5.2 Model Definitions</h3>
<p>Five prediction strategies are evaluated:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Type</th>
<th>Key Hyperparameters</th>
<th>Imbalance Strategy</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Logistic Regression</td>
<td>Linear baseline</td>
<td>C=0.5, max_iter=2000, solver=lbfgs</td>
<td>class_weight=‘balanced’</td>
</tr>
<tr class="even">
<td>Random Forest</td>
<td>Bagging ensemble</td>
<td>400 trees, max_depth=10, min_samples_leaf=3</td>
<td>class_weight=‘balanced’ + SMOTE</td>
</tr>
<tr class="odd">
<td>XGBoost</td>
<td>Boosting</td>
<td>500 trees, depth=4, lr=0.05, early stopping=30</td>
<td>scale_pos_weight=19.5 + SMOTE</td>
</tr>
<tr class="even">
<td>Soft Voting</td>
<td>Probability averaging</td>
<td>Mean of LR + RF + XGB probabilities</td>
<td>Inherited from base models</td>
</tr>
<tr class="odd">
<td>Stacking Ensemble</td>
<td>Meta-learning</td>
<td>LR meta-learner on 5-fold OOF predictions</td>
<td>class_weight=‘balanced’ (meta)</td>
</tr>
</tbody>
</table>
</section>
<section id="stacking-design-out-of-fold-meta-learning" class="level3">
<h3 class="anchored" data-anchor-id="stacking-design-out-of-fold-meta-learning">5.3 Stacking Design: Out-of-Fold Meta-Learning</h3>
<p>The stacking ensemble uses out-of-fold (OOF) predictions to prevent target leakage in the meta learning stage. Under 5-fold stratified cross validation, each base model trains on 4 folds and generates probability predictions for the held out 5th fold. The concatenated OOF predictions form a (n_train × 3) meta feature matrix used to train the Logistic Regression meta learner. Test predictions are averaged across all 5 fold models per base learner. This design ensures the meta learner never trains on targets it has already seen.</p>
</section>
<section id="threshold-tuning" class="level3">
<h3 class="anchored" data-anchor-id="threshold-tuning">5.4 Threshold Tuning</h3>
<p>Instead of using the default 0.50 cutoff, thresholds are tuned on a held out validation set (16% of total data) using a grid search from 0.01 to 0.99. Two operating modes are defined:</p>
<ul>
<li><strong>High Sensitivity mode</strong> (min_precision = 0.08): Maximises recall subject to precision ≥ 0.08. For every 12 patients flagged for stroke risk, at least 1 must be a true case. Designed for population level screening where missing a stroke is catastrophic.</li>
<li><strong>Balanced mode</strong> (min_precision = 0.10): Maximises F1-score subject to precision ≥ 0.10. Suited for clinical settings where false positives carry non trivial follow up costs.</li>
</ul>
</section>
<section id="data-split-strategy" class="level3">
<h3 class="anchored" data-anchor-id="data-split-strategy">5.5 Data Split Strategy</h3>
<p>A three-way split was used to ensure complete separation of model training, threshold selection, and final evaluation:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Split</th>
<th>Patients</th>
<th>Stroke Cases</th>
<th>Purpose</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Inner Train</td>
<td>3,270 (64%)</td>
<td>~159 (4.9%)</td>
<td>Base model training, OOF stacking meta-features</td>
</tr>
<tr class="even">
<td>Validation</td>
<td>818 (16%)</td>
<td>~40 (4.9%)</td>
<td>Threshold tuning — never used for model training</td>
</tr>
<tr class="odd">
<td>Test</td>
<td>1,022 (20%)</td>
<td>50 (4.9%)</td>
<td>Final evaluation — held out throughout all modelling stages</td>
</tr>
</tbody>
</table>
</section>
<section id="evaluation-metrics" class="level3">
<h3 class="anchored" data-anchor-id="evaluation-metrics">5.6 Evaluation Metrics</h3>
<p>Given the clinical context, metrics are prioritised as follows:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Priority</th>
<th>Rationale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Recall / Sensitivity</td>
<td><strong>Critical</strong></td>
<td>Minimises missed strokes — the highest cost clinical error</td>
</tr>
<tr class="even">
<td>AUC-PR / Average Precision</td>
<td>Primary</td>
<td>Most informative for imbalanced binary classification</td>
</tr>
<tr class="odd">
<td>ROC-AUC</td>
<td>Primary</td>
<td>Overall discriminative ability across all thresholds</td>
</tr>
<tr class="even">
<td>F1-Score</td>
<td>Secondary</td>
<td>Harmonic mean of precision and recall</td>
</tr>
<tr class="odd">
<td>Precision</td>
<td>Secondary</td>
<td>Determines clinical feasibility of follow-up</td>
</tr>
<tr class="even">
<td>Confusion Matrix</td>
<td>Supplementary</td>
<td>Absolute counts for direct clinical interpretation</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="final-results" class="level2">
<h2 class="anchored" data-anchor-id="final-results">6. Final Results</h2>
<section id="model-performance-comparison" class="level3">
<h3 class="anchored" data-anchor-id="model-performance-comparison">6.1 Model Performance Comparison</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals/07_model_metric_heatmap.png" class="img-fluid figure-img" alt="Model metric heatmap"></p>
<figcaption>Model metric heatmap comparing all five models across key evaluation metrics.</figcaption>
</figure>
</div>
<p><strong>Table 6.1: Final Test Set Results — High Sensitivity Mode (n=1,022, 50 stroke cases)</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Threshold</th>
<th>AUC-ROC</th>
<th>AUC-PR</th>
<th>Recall</th>
<th>Precision</th>
<th>F1</th>
<th>Missed (FN)</th>
<th>False Alarms (FP)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Logistic Regression</td>
<td>0.13</td>
<td>0.833</td>
<td>0.210</td>
<td><strong>0.940</strong></td>
<td>0.079</td>
<td>0.146</td>
<td><strong>3</strong></td>
<td>546</td>
</tr>
<tr class="even">
<td>Random Forest</td>
<td>0.02</td>
<td>0.818</td>
<td>0.183</td>
<td>0.880</td>
<td>0.084</td>
<td>0.154</td>
<td>6</td>
<td>479</td>
</tr>
<tr class="odd">
<td>XGBoost</td>
<td>0.56</td>
<td>0.803</td>
<td>0.168</td>
<td>0.460</td>
<td>0.168</td>
<td>0.246</td>
<td>27</td>
<td><strong>114</strong></td>
</tr>
<tr class="even">
<td>Soft Voting</td>
<td>0.24</td>
<td>0.828</td>
<td>0.191</td>
<td>0.820</td>
<td>0.106</td>
<td>0.188</td>
<td>9</td>
<td>346</td>
</tr>
<tr class="odd">
<td><strong>Stacking Ensemble</strong></td>
<td>0.12</td>
<td><strong>0.838</strong></td>
<td><strong>0.215</strong></td>
<td>0.920</td>
<td>0.082</td>
<td>0.150</td>
<td>4</td>
<td>516</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p>All thresholds were determined exclusively on the validation set. Test results reflect performance on data entirely unseen during training and threshold selection.</p>
</blockquote>
<p><strong>Table 6.2: Final Test Set Results — Balanced Mode</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Threshold</th>
<th>AUC-ROC</th>
<th>AUC-PR</th>
<th>Recall</th>
<th>Precision</th>
<th>F1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Logistic Regression</td>
<td>—</td>
<td>0.833</td>
<td>0.210</td>
<td>0.420</td>
<td>0.223</td>
<td>0.292</td>
</tr>
<tr class="even">
<td>Random Forest</td>
<td>—</td>
<td>0.818</td>
<td>0.183</td>
<td>0.420</td>
<td>0.219</td>
<td>0.288</td>
</tr>
<tr class="odd">
<td>XGBoost</td>
<td>—</td>
<td>0.803</td>
<td>0.168</td>
<td>0.040</td>
<td>0.154</td>
<td>0.064</td>
</tr>
<tr class="even">
<td>Soft Voting</td>
<td>—</td>
<td>0.828</td>
<td>0.191</td>
<td>0.260</td>
<td>0.200</td>
<td>0.226</td>
</tr>
<tr class="odd">
<td><strong>Stacking Ensemble</strong></td>
<td>—</td>
<td><strong>0.838</strong></td>
<td><strong>0.215</strong></td>
<td>0.780</td>
<td>0.194</td>
<td><strong>0.311</strong></td>
</tr>
</tbody>
</table>
<p>The Balanced mode results confirm that Stacking Ensemble is the superior model when both precision and recall are weighted — it achieves the highest F1 (0.311) while maintaining strong recall (0.780).</p>
</section>
<section id="roc-curves-precision-recall-curves-and-feature-importance" class="level3">
<h3 class="anchored" data-anchor-id="roc-curves-precision-recall-curves-and-feature-importance">6.2 ROC Curves, Precision-Recall Curves, and Feature Importance</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals/stroke_ensemble_roc_pr_fi.png" class="img-fluid figure-img" alt="ROC, PR, and feature importance plot"></p>
<figcaption>ROC curves (left), Precision-Recall curves (centre), and XGBoost feature importance (right) for all five models. The Stacking Ensemble achieves the highest AUC-PR (0.215).</figcaption>
</figure>
</div>
<p>The Precision-Recall curves are the primary performance indicator for this imbalanced dataset — they directly measure the precision-recall tradeoff on the minority class, unlike ROC curves which can appear favourable even when performance on the minority class is poor. The Stacking Ensemble (red dashed) achieves the highest Average Precision of 0.215, which is 4.4 times above the naive baseline (4.9% prevalence).</p>
</section>
<section id="confusion-matrices" class="level3">
<h3 class="anchored" data-anchor-id="confusion-matrices">6.3 Confusion Matrices</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals/stroke_ensemble_confusion.png" class="img-fluid figure-img" alt="Confusion matrices for all models"></p>
<figcaption>Confusion matrices for all five models under High Sensitivity operating mode. Logistic Regression (top-left) achieves recall=0.940 with only 3 missed strokes. Stacking Ensemble (bottom-right) achieves recall=0.920 with 4 missed strokes and the highest AUC-PR.</figcaption>
</figure>
</div>
<p><strong>Clinical interpretation of confusion matrices:</strong></p>
<ul>
<li><strong>Logistic Regression</strong>: 43 strokes caught, 3 missed, 546 false alarms. Best recall but highest false alarm rate. Optimal for maximum sensitivity screening.</li>
<li><strong>Stacking Ensemble</strong>: 46 strokes caught, 4 missed, 516 false alarms. Best AUC-PR and second-highest recall. Optimal for overall precision-recall balance.</li>
<li><strong>XGBoost alone</strong>: 23 strokes caught, 27 missed. Only 114 false alarms but misses more than half of all stroke patients — unsuitable as a screening model despite high individual precision.</li>
</ul>
</section>
<section id="threshold-sensitivity-analysis" class="level3">
<h3 class="anchored" data-anchor-id="threshold-sensitivity-analysis">6.4 Threshold Sensitivity Analysis</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals/stroke_ensemble_threshold_sweep.png" class="img-fluid figure-img" alt="Threshold sweep for stacking"></p>
<figcaption>Threshold sweep for the Stacking Ensemble on the test set. Black dashed line (thr=0.12) marks High Sensitivity operating point. Purple dashed line (thr=0.67) marks Balanced operating point.</figcaption>
</figure>
</div>
<p>The threshold sweep reveals that the Stacking Ensemble maintains recall above 0.80 for any threshold below approximately 0.67, demonstrating robust sensitivity across a wide operating range. The precision floor of 0.08 (orange dotted line) ensures the model remains clinically viable — at thresholds below this floor, nearly all patients are flagged, which is operationally unworkable. The plateau of stable high recall between threshold 0.12 and 0.67 gives clinical teams flexibility to adjust the operating point based on available follow-up capacity.</p>
</section>
<section id="xgboost-feature-importance" class="level3">
<h3 class="anchored" data-anchor-id="xgboost-feature-importance">6.5 XGBoost Feature Importance</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="visuals/08_xgb_feature_importance.png" class="img-fluid figure-img" alt="XGBoost feature importance"></p>
<figcaption>XGBoost feature importance ranked by gain metric, showing engineered features dominating the top ranks.</figcaption>
</figure>
</div>
<p><strong>Table 6.3: Top 9 XGBoost Feature Importance Scores</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Rank</th>
<th>Feature</th>
<th>Importance</th>
<th>Type</th>
<th>Clinical Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td><code>age_squared</code></td>
<td>0.156</td>
<td>Engineered</td>
<td>Non-linear age acceleration of stroke risk</td>
</tr>
<tr class="even">
<td>2</td>
<td><code>is_senior</code></td>
<td>0.128</td>
<td>Engineered</td>
<td>Binary flag: age ≥ 55 threshold effect</td>
</tr>
<tr class="odd">
<td>3</td>
<td><code>age</code></td>
<td>0.115</td>
<td>Original</td>
<td>Primary biological risk factor</td>
</tr>
<tr class="even">
<td>4</td>
<td><code>cvd_count</code></td>
<td>0.098</td>
<td>Engineered</td>
<td>Combined hypertension + heart disease burden</td>
</tr>
<tr class="odd">
<td>5</td>
<td><code>residence</code></td>
<td>0.087</td>
<td>Original</td>
<td>Urban/rural healthcare access differences</td>
</tr>
<tr class="even">
<td>6</td>
<td><code>gender</code></td>
<td>0.079</td>
<td>Original</td>
<td>Sex-based physiological differences</td>
</tr>
<tr class="odd">
<td>7</td>
<td><code>has_hypertension</code></td>
<td>0.072</td>
<td>Original</td>
<td>Strongest modifiable risk factor</td>
</tr>
<tr class="even">
<td>8</td>
<td><code>smoking_habit</code></td>
<td>0.063</td>
<td>Original</td>
<td>Accelerates atherosclerosis</td>
</tr>
<tr class="odd">
<td>9</td>
<td><code>employment_type</code></td>
<td>0.055</td>
<td>Original</td>
<td>Socioeconomic and stress-related proxy</td>
</tr>
</tbody>
</table>
<p>Three of the top four features are engineered rather than original clinical features. <code>age_squared</code> and <code>is_senior</code> together account for approximately 28.4% of total model importance, confirming that the non-linear and threshold effects of age contribute more predictive signal than the raw age value alone. <code>cvd_count</code> outperforms either of its component features independently, validating the clinical insight that cumulative cardiovascular burden is more predictive than any single comorbidity.</p>
</section>
<section id="key-performance-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="key-performance-interpretation">6.6 Key Performance Interpretation</h3>
<ul>
<li>Logistic Regression achieves the highest recall (0.940) in High Sensitivity mode — only 3 stroke patients missed from 50 in the test set</li>
<li>Stacking Ensemble gives the best overall AUC-PR (0.215) and highest F1 in Balanced mode (0.311)</li>
<li>XGBoost alone is not the strongest recall model in this small minority-class regime — see Section 7.1 for explanation</li>
<li>Threshold tuning materially changes the operational behaviour of every model — the default 0.50 threshold is inappropriate for this clinical task</li>
<li>Engineered features consistently outrank original clinical features in XGBoost importance, validating the feature engineering process</li>
</ul>
<hr>
</section>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">7. Discussion</h2>
<section id="why-logistic-regression-outperforms-xgboost-on-recall" class="level3">
<h3 class="anchored" data-anchor-id="why-logistic-regression-outperforms-xgboost-on-recall">7.1 Why Logistic Regression Outperforms XGBoost on Recall</h3>
<p>The most striking result is that Logistic Regression outperforms XGBoost on recall (0.940 vs 0.460) despite XGBoost being a more complex algorithm. This is a direct manifestation of the bias-variance tradeoff under small minority class conditions. With only 249 genuine stroke training cases, XGBoost has insufficient minority-class data to reliably learn the complex non-linear decision boundaries that make gradient boosting superior on larger datasets. In this regime, the model exhibits high variance — it overfits to specific combinations of features seen in the 249 training stroke cases and fails to generalise. Logistic Regression, being a simpler regularised linear model, finds the dominant separating boundary (governed by age and comorbidity features) and extrapolates it more reliably to unseen stroke patients.</p>
<p>This finding is consistent with established literature on medical machine learning: complex models do not always outperform simpler ones when minority class training data is scarce. It also explains why the Stacking Ensemble bridges the gap — by combining Logistic Regression’s reliable linear boundary with Random Forest and XGBoost’s non-linear contributions, the meta-learner achieves better overall precision-recall performance than any individual model alone.</p>
</section>
<section id="clinical-interpretation-of-key-findings" class="level3">
<h3 class="anchored" data-anchor-id="clinical-interpretation-of-key-findings">7.2 Clinical Interpretation of Key Findings</h3>
<p>The strongest findings are consistent with established medical knowledge:</p>
<ul>
<li><strong>Age</strong> is the dominant non-modifiable risk factor. The non-linear acceleration captured by <code>age_squared</code> is the most important feature, confirming that risk grows exponentially rather than linearly after middle age. A patient aged 70 does not have twice the stroke risk of a 35-year-old but many times higher.</li>
<li><strong>Hypertension and heart disease</strong> compound risk. The <code>cvd_count</code> feature, which represents cumulative cardiovascular burden, outperforms either comorbidity independently, consistent with the clinical understanding that stroke risk factors multiply rather than add.</li>
<li><strong>Glucose and BMI</strong> matter primarily through interaction terms. <code>glucose_x_bmi</code> captures the joint metabolic risk of hyperglycaemia and obesity — a subgroup for whom combined dietary and pharmacological intervention may yield the greatest stroke prevention benefit.</li>
<li><strong>Smoking status</strong> adds useful signal, particularly where data quality is mixed. The <code>unknown</code> smoking category shows elevated stroke rates, likely capturing patients reluctant to disclose smoking status due to existing health concerns.</li>
</ul>
</section>
<section id="high-risk-patient-profile" class="level3">
<h3 class="anchored" data-anchor-id="high-risk-patient-profile">7.3 High-Risk Patient Profile</h3>
<p>Synthesising EDA, statistical tests, and feature importance, four characteristics define the highest-risk profile:</p>
<ol type="1">
<li>Age above 60 years <em>(non-modifiable — primary stratification criterion)</em></li>
<li>Presence of hypertension <em>(modifiable via antihypertensive therapy)</em></li>
<li>Elevated glucose above 140 mg/dL <em>(modifiable via diet, exercise, pharmacotherapy)</em></li>
<li>Presence of heart disease as co-morbidity <em>(managed via cardiac care protocols)</em></li>
</ol>
<p>Patients meeting three or four of these criteria represent the priority target for intensive stroke prevention programmes.</p>
</section>
<section id="deployment-considerations" class="level3">
<h3 class="anchored" data-anchor-id="deployment-considerations">7.4 Deployment Considerations</h3>
<p>For screening use, a high-recall model is more useful than one optimised for precision. A precision of 0.08 in High Sensitivity mode means approximately 1 in 12 patients flagged for stroke risk is a confirmed case. This is clinically defensible for three reasons:</p>
<ol type="1">
<li>The consequence of a missed stroke is catastrophic and irreversible</li>
<li>The follow-up assessment triggered by a positive flag is non-invasive clinical review, not an invasive procedure</li>
<li>Precision values of 5–10% are consistent with accepted screening programmes in other medical domains, including mammography</li>
</ol>
<p>A two-stage protocol is recommended: the model flags high-risk patients as a first-line automated screen, then clinicians review the flagged group using their clinical judgement. The model output should be treated as a decision-support tool rather than a diagnostic conclusion.</p>
<hr>
</section>
</section>
<section id="limitations" class="level2">
<h2 class="anchored" data-anchor-id="limitations">8. Limitations</h2>
<ul>
<li><strong>Small minority class</strong>: With only 249 genuine stroke cases, complex models cannot learn reliable minority-class decision boundaries. More stroke data would significantly improve all models.</li>
<li><strong>Single-source dataset</strong>: External validation on an independent cohort from a different healthcare setting is required before clinical deployment.</li>
<li><strong>No temporal data</strong>: The dataset is a single-timepoint snapshot. Longitudinal tracking of changes in blood pressure, glucose, and BMI would substantially improve predictive power.</li>
<li><strong>Unknown smoking status</strong>: A significant proportion of patients have <code>smoking_habit = unknown</code>, limiting the model’s ability to fully leverage this modifiable risk factor.</li>
<li><strong>Artificial dataset balance</strong>: The pre-release duplication of all 249 stroke records required detection and correction. Any analyses performed on the original 9,722-record dataset without deduplication should be treated with caution.</li>
</ul>
<hr>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">9. Conclusion</h2>
<p>This project develops a leakage-safe stroke prediction workflow on a genuinely imbalanced dataset of 5,110 unique patients following the detection and removal of 4,612 artificially duplicated records. The pipeline addresses the 4.87% stroke prevalence through SMOTE oversampling, class-weight adjustment, and validation-set threshold tuning — three complementary strategies for handling the 19.5:1 class imbalance.</p>
<p>Five models were trained and evaluated. Under the High Sensitivity operating mode, Logistic Regression achieved the highest recall (0.940) with only 3 missed stroke cases. The Stacking Ensemble achieved the best overall precision-recall performance (AUC-PR = 0.215) with recall of 0.920. The finding that a simpler regularised linear model outperforms complex boosting individually on recall — due to the bias-variance tradeoff under small minority class conditions — is a meaningful methodological insight for healthcare machine learning practitioners.</p>
<p>The visual analysis, statistical testing, and feature importance analysis all reinforce the same clinical conclusion: age and cardiovascular burden dominate stroke risk in this dataset, with non-linear and interaction features providing the most discriminatory predictive signal.</p>
<hr>
</section>
<section id="recommendations" class="level2">
<h2 class="anchored" data-anchor-id="recommendations">10. Recommendations</h2>
<ul>
<li>Use the model as a screening aid, not a diagnostic replacement</li>
<li>Deploy a two-stage protocol: automated screening followed by clinical review of flagged patients</li>
<li>Prioritise patients with elevated age, hypertension, and heart disease for intensive monitoring</li>
<li>Monitor glucose and BMI carefully in adults aged above 55, regardless of presenting symptoms</li>
<li>Invest in smoking cessation programmes as the most readily modifiable lifestyle risk factor</li>
<li>Validate the model on a second real-world cohort before any clinical deployment</li>
<li>Extend future work with SHAP explanations and probability calibration for better clinical communication</li>
</ul>
<hr>
</section>
<section id="future-work" class="level2">
<h2 class="anchored" data-anchor-id="future-work">11. Future Work</h2>
<ul>
<li><strong>External validation</strong>: Test on an independent patient cohort with natural class imbalance to assess real-world generalisability</li>
<li><strong>SHAP-based interpretability</strong>: Individual patient-level risk factor explanation — critical for clinical acceptance and regulatory compliance of ML-based medical tools</li>
<li><strong>Probability calibration</strong>: Calibrated probability outputs to provide clinicians with reliable stroke probability estimates rather than binary risk flags</li>
<li><strong>Longitudinal modelling</strong>: Incorporate temporal feature trajectories tracking changes in blood pressure, glucose, and BMI over time rather than relying on single-point measurements</li>
</ul>
<hr>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>[1] World Health Organization, “Stroke, Cerebrovascular accident,” WHO, 2023.<br>
[2] Centers for Disease Control and Prevention, “Stroke Facts and Statistics,” CDC, 2023.<br>
[3] Global Burden of Disease Study, “Global, regional, and national burden of stroke,” <em>The Lancet Neurology</em>, 2021.<br>
[4] S. K. Pandey et al., “Machine learning techniques for stroke prediction: A review,” <em>IEEE Access</em>, 2020.<br>
[5] N. V. Chawla et al., “SMOTE: Synthetic minority over-sampling technique,” <em>Journal of Artificial Intelligence Research</em>, 2002.<br>
[6] T. Chen and C. Guestrin, “XGBoost: A scalable tree boosting system,” <em>KDD</em>, 2016.</p>
<hr>
</section>
<section id="appendix-contribution-statement" class="level2">
<h2 class="anchored" data-anchor-id="appendix-contribution-statement">Appendix: Contribution Statement</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Member Name</th>
<th>Student ID</th>
<th>Primary Contributions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>R.P.M. Vithanage</td>
<td>[ID]</td>
<td>Data cleaning, deduplication, BMI imputation, EDA, statistical testing</td>
</tr>
<tr class="even">
<td>S.E.N. S. Silva</td>
<td>[ID]</td>
<td>Feature engineering, model development, ensemble design, threshold tuning, visualisations, report writing</td>
</tr>
</tbody>
</table>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>